augmentation:
  enabled: false
  mixup: 0.0
  mosaic: 0.0
model:
  batch_size: 1
  device: mps
  format: onnx
  imgsz: 640
  path: /Users/subhashmothukurigmail.com/Projects/Modular Vechical Speed Tracking/src/finetuning/results/vehicle_detection_v1/weights/best.pt
optimization:
  async_processing: true
  dynamic_shapes: true
  half_precision: true
  resize_factor: 1.0
  skip_frames: 1
performance:
  max_latency_ms: 33
  memory_limit_mb: 1024
  target_fps: 30
